# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-29 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='none', max_length=50)),
                ('slug', models.CharField(default='none', max_length=50)),
                ('product_description', models.TextField(default='none', max_length=5000)),
            ],
        ),
    ]
