# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-29 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_thumbnail',
            field=models.ImageField(blank=True, default='stars.png', upload_to=''),
        ),
    ]
