# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-04-22 22:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0005_products_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='none', max_length=50)),
                ('slug', models.CharField(default='none', max_length=50)),
                ('product_description', models.TextField(default='none', max_length=5000)),
                ('product_thumbnail', models.ImageField(blank=True, default='stars.png', upload_to='')),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='products',
            name='author',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.AlterUniqueTogether(
            name='productcategory',
            unique_together=set([('category',)]),
        ),
        migrations.AlterUniqueTogether(
            name='productbrand',
            unique_together=set([('brand',)]),
        ),
        migrations.AddField(
            model_name='product',
            name='product_brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ProductBrand'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ProductCategory'),
        ),
    ]
